In [1]:
from constants import DATA_ROOT_PATH_NAME, BANDPASS, HAMPEL_WINDOW_SIZE, HAMPEL_N_SIGMA, CROP_TMIN, CROP_TMAX, LOCAL_DETREND_WINDOW_SEC, LOCAL_DETREND_STEP_SEC, ASR_CUTOFF, ASR_BLOCKSIZE, ASR_WIN_LEN, ASR_WIN_OVERLAP, ASR_MAX_DROPOUT_FRACTION, ASR_MIN_CLEAN_FRACTION, ASR_MAX_BAD_CHANS

from preprocessing.step.bandpass import BandpassFilterStep
from preprocessing.step.detrend import LocalDetrendStep
from preprocessing.step.hampel import HampelFilterStep
from preprocessing.step.asr import ASRStep
from preprocessing.step.crop import CropStep

from preprocessing.pipeline import PreprocessingPipeline
import numpy as np

from features.factory import FeatureExtractionEngine, FeatureExtractionConfig
from features.categories import FeatureCategory

from eeg.data import EEGRecordedDataProvider

from features.visualization import TopomapFactory



%load_ext autoreload
%autoreload 2

# Création des 2 datasets de features

In [ ]:
recordings = EEGRecordedDataProvider.build(DATA_ROOT_PATH_NAME)

/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-001_task-eyesclosed.

The search_str was "data/sub-001/**/eeg/sub-001*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: F
Age: 57
Group: A
MMSE: 16
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-002_task-eyesclosed.

The search_str was "data/sub-002/**/eeg/sub-002*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: F
Age: 78
Group: A
MMSE: 22
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-003_task-eyesclosed.

The search_str was "data/sub-003/**/eeg/sub-003*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: M
Age: 70
Group: A
MMSE: 14
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-004_task-eyesclosed.

The search_str was "data/sub-004/**/eeg/sub-004*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: F
Age: 67
Group: A
MMSE: 20
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-005_task-eyesclosed.

The search_str was "data/sub-005/**/eeg/sub-005*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: M
Age: 70
Group: A
MMSE: 22
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-006_task-eyesclosed.

The search_str was "data/sub-006/**/eeg/sub-006*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: F
Age: 61
Group: A
MMSE: 14
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-007_task-eyesclosed.

The search_str was "data/sub-007/**/eeg/sub-007*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: F
Age: 79
Group: A
MMSE: 20
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-008_task-eyesclosed.

The search_str was "data/sub-008/**/eeg/sub-008*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: M
Age: 62
Group: A
MMSE: 16
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-009_task-eyesclosed.

The search_str was "data/sub-009/**/eeg/sub-009*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: F
Age: 77
Group: A
MMSE: 23
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-010_task-eyesclosed.

The search_str was "data/sub-010/**/eeg/sub-010*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: M
Age: 69
Group: A
MMSE: 20
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-011_task-eyesclosed.

The search_str was "data/sub-011/**/eeg/sub-011*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: M
Age: 71
Group: A
MMSE: 22
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-012_task-eyesclosed.

The search_str was "data/sub-012/**/eeg/sub-012*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: M
Age: 63
Group: A
MMSE: 18
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-013_task-eyesclosed.

The search_str was "data/sub-013/**/eeg/sub-013*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: F
Age: 64
Group: A
MMSE: 20
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-014_task-eyesclosed.

The search_str was "data/sub-014/**/eeg/sub-014*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: M
Age: 77
Group: A
MMSE: 14
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-015_task-eyesclosed.

The search_str was "data/sub-015/**/eeg/sub-015*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: M
Age: 61
Group: A
MMSE: 18
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-016_task-eyesclosed.

The search_str was "data/sub-016/**/eeg/sub-016*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: F
Age: 68
Group: A
MMSE: 14
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-017_task-eyesclosed.

The search_str was "data/sub-017/**/eeg/sub-017*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: F
Age: 61
Group: A
MMSE: 6
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-018_task-eyesclosed.

The search_str was "data/sub-018/**/eeg/sub-018*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: F
Age: 73
Group: A
MMSE: 23
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-019_task-eyesclosed.

The search_str was "data/sub-019/**/eeg/sub-019*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: F
Age: 62
Group: A
MMSE: 14
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-020_task-eyesclosed.

The search_str was "data/sub-020/**/eeg/sub-020*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: M
Age: 71
Group: A
MMSE: 4
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-021_task-eyesclosed.

The search_str was "data/sub-021/**/eeg/sub-021*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: M
Age: 79
Group: A
MMSE: 22
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-022_task-eyesclosed.

The search_str was "data/sub-022/**/eeg/sub-022*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: F
Age: 68
Group: A
MMSE: 20
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-023_task-eyesclosed.

The search_str was "data/sub-023/**/eeg/sub-023*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: M
Age: 60
Group: A
MMSE: 16
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-024_task-eyesclosed.

The search_str was "data/sub-024/**/eeg/sub-024*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: F
Age: 69
Group: A
MMSE: 20
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-025_task-eyesclosed.

The search_str was "data/sub-025/**/eeg/sub-025*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: F
Age: 79
Group: A
MMSE: 20
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-026_task-eyesclosed.

The search_str was "data/sub-026/**/eeg/sub-026*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: F
Age: 61
Group: A
MMSE: 18
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-027_task-eyesclosed.

The search_str was "data/sub-027/**/eeg/sub-027*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: F
Age: 67
Group: A
MMSE: 16
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-028_task-eyesclosed.

The search_str was "data/sub-028/**/eeg/sub-028*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: M
Age: 49
Group: A
MMSE: 20
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-029_task-eyesclosed.

The search_str was "data/sub-029/**/eeg/sub-029*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: F
Age: 53
Group: A
MMSE: 16
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-030_task-eyesclosed.

The search_str was "data/sub-030/**/eeg/sub-030*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: F
Age: 56
Group: A
MMSE: 20
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-031_task-eyesclosed.

The search_str was "data/sub-031/**/eeg/sub-031*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: F
Age: 67
Group: A
MMSE: 22
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-032_task-eyesclosed.

The search_str was "data/sub-032/**/eeg/sub-032*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: F
Age: 59
Group: A
MMSE: 20
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-033_task-eyesclosed.

The search_str was "data/sub-033/**/eeg/sub-033*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: F
Age: 72
Group: A
MMSE: 20
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-034_task-eyesclosed.

The search_str was "data/sub-034/**/eeg/sub-034*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: F
Age: 75
Group: A
MMSE: 18
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-035_task-eyesclosed.

The search_str was "data/sub-035/**/eeg/sub-035*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: F
Age: 57
Group: A
MMSE: 22
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-036_task-eyesclosed.

The search_str was "data/sub-036/**/eeg/sub-036*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: F
Age: 58
Group: A
MMSE: 9
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-037_task-eyesclosed.

The search_str was "data/sub-037/**/eeg/sub-037*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: M
Age: 57
Group: C
MMSE: 30
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-038_task-eyesclosed.

The search_str was "data/sub-038/**/eeg/sub-038*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: M
Age: 62
Group: C
MMSE: 30
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-039_task-eyesclosed.

The search_str was "data/sub-039/**/eeg/sub-039*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: M
Age: 70
Group: C
MMSE: 30
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-040_task-eyesclosed.

The search_str was "data/sub-040/**/eeg/sub-040*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: M
Age: 61
Group: C
MMSE: 30
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-041_task-eyesclosed.

The search_str was "data/sub-041/**/eeg/sub-041*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: F
Age: 77
Group: C
MMSE: 30
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-042_task-eyesclosed.

The search_str was "data/sub-042/**/eeg/sub-042*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: M
Age: 74
Group: C
MMSE: 30
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Did not find any events.tsv associated with sub-043_task-eyesclosed.

The search_str was "data/sub-043/**/eeg/sub-043*events.tsv"
  raw : mne.io.Raw = read_raw_bids(bids_path=bids_path, verbose=False)
/mnt/ssd2/pth-eeg/eeg/eeg/data.py:121: RuntimeWarning: Unable to map the following column(s) to to MNE:
Gender: M
Age: 72
Group: C

In [ ]:
asr_pipeline = PreprocessingPipeline(name="ASR",
                                        steps=[
                                                BandpassFilterStep(BANDPASS),
                                                CropStep(tmin=CROP_TMIN, tmax=CROP_TMAX),
                                                ASRStep(cutoff=ASR_CUTOFF, blocksize=ASR_BLOCKSIZE, win_len=ASR_WIN_LEN, win_overlap=ASR_WIN_OVERLAP, max_dropout_fraction=ASR_MAX_DROPOUT_FRACTION, min_clean_fraction=ASR_MIN_CLEAN_FRACTION, max_bad_chans=ASR_MAX_BAD_CHANS)
                                                ])

dethamp_pipeline = PreprocessingPipeline(name="det-hamp",
                                        steps=[ 
                                                BandpassFilterStep(BANDPASS),
                                                CropStep(tmin=CROP_TMIN, tmax=CROP_TMAX),
                                                LocalDetrendStep(window_sec=LOCAL_DETREND_WINDOW_SEC, step_sec=LOCAL_DETREND_STEP_SEC),
                                                HampelFilterStep(window_size=HAMPEL_WINDOW_SIZE, n_sigma=HAMPEL_N_SIGMA)
                                                ])

In [4]:
recorded_eeg = recordings[14]
asr_processed_eeg = asr_pipeline.compute(recorded_eeg)
dethamp_processed_eeg = dethamp_pipeline.compute(recorded_eeg)

In [ ]:
categories_to_extract = [FeatureCategory.WAVELET, FeatureCategory.TEMPORAL, FeatureCategory.POWER_RATIO, FeatureCategory.SPECTRAL]
config = FeatureExtractionConfig(categories_to_extract=categories_to_extract, wamp_threshold=10e-9, ppc_epoch_duration=2)
feature_extraction_engine = FeatureExtractionEngine(config=config)

dethamp_processed_extraction_result = feature_extraction_engine.extract(dethamp_processed_eeg)


asr_processed_extraction_result = feature_extraction_engine.extract(asr_processed_eeg)

/mnt/ssd2/pth-eeg/eeg/eeg/ppc.py:395: RuntimeWarning: fmin=1.000 Hz corresponds to 2.000 < 5 cycles based on the epoch length 2.000 sec, need at least 5.000 sec epochs or fmin=2.500. Spectrum estimate will be unreliable.
  conn: Connectivity = spectral_connectivity_epochs(
/mnt/ssd2/pth-eeg/eeg/eeg/ppc.py:395: RuntimeWarning: fmin=1.000 Hz corresponds to 2.000 < 5 cycles based on the epoch length 2.000 sec, need at least 5.000 sec epochs or fmin=2.500. Spectrum estimate will be unreliable.
  conn: Connectivity = spectral_connectivity_epochs(

# Import de toutes les features de tous les participants

In [2]:
from features.io import FeaturesDatasetIO
dethamp_dataset = FeaturesDatasetIO.load("computed_data/dethamp")
asr_dataset = FeaturesDatasetIO.load("computed_data/asr")

In [3]:
dethamp_dataset.feature_names

['theta_beta_ratio',
 'theta_alpha_ratio',
 'gamma_alpha_ratio',
 'spectral_power_ratio',
 'alpha_dominant_frequency',
 'gamma_dominant_frequency',
 'spectral_rolloff',
 'spectral_centroid',
 'spectral_spread',
 'spectral_flux',
 'spectral_skewness',
 'spectral_kurtosis',
 'variance',
 'skewness',
 'kurtosis',
 'peak_amplitude',
 'shape_factor',
 'impulse_factor',
 'crest_factor',
 'clearance_factor',
 'willison_amplitude',
 'zero_crossing_rate',
 'wavelet_energy_approximate',
 'wavelet_energy_detail',
 'relative_wavelet_energy',
 'wavelet_packet_energy_approximate',
 'wavelet_packet_energy_detail',
 'relative_wavelet_packet_energy']

In [4]:
dethamp_dataset.to_long_dataframe()

,channel,feature,value,subject_id,subject_age,subject_health,subject_mmse
0,Fp1,theta_beta_ratio,0.008586,082,63,Frontotemporal Dementia,27
1,Fp2,theta_beta_ratio,0.009132,082,63,Frontotemporal Dementia,27
2,F3,theta_beta_ratio,0.007954,082,63,Frontotemporal Dementia,27
3,F4,theta_beta_ratio,0.011192,082,63,Frontotemporal Dementia,27
4,C3,theta_beta_ratio,0.008844,082,63,Frontotemporal Dementia,27
...,...,...,...,...,...,...,...
46811,T5,relative_wavelet_packet_energy,0.933886,022,68,Alzheimer,20
46812,T6,relative_wavelet_packet_energy,0.932540,022,68,Alzheimer,20
46813,Fz,relative_wavelet_packet_energy,0.938957,022,68,Alzheimer,20
46814,Cz,relative_wavelet_packet_energy,0.935803,022,68,Alzheimer,20
46815,Pz,relative_wavelet_packet_energy,0.928721,022,68,Alzheimer,20

# Tests statistiques

In [38]:
from stats.queries import QueryFactoryConfig, QueryFactory
from stats.runner import StatisticalTestRunner
from stats.correction.fdr import FDRCorrector

factory = QueryFactory(
    QueryFactoryConfig.from_lists(
        subject_variables={"subject_age", "subject_mmse", "subject_id", "subject_mmse", "subject_health"},
        eeg_features=dethamp_dataset.feature_names,
    )
)

query = factory.compare_groups(
    target="shape_factor",
    group_col="subject_health",
    group_a="Healthy",
    group_b="Alzheimer",
    test_kind="wilcoxon_rank_sum",
    scope="all_channels"
)



raw_result_set = StatisticalTestRunner.run(query, dethamp_dataset)
corrected_result_set = FDRCorrector.correct(raw_result_set)

corrected_result_set.to_dataframe()

,key,target,statistic,p_value,p_value_corrected,correction_method,alpha,reject_null,test_name,n_x,n_y,x_name,y_name,label
0,Fp1,shape_factor,-2.098290,0.035880,0.219890,fdr_bh,0.05,False,wilcoxon-rank-sum,29,36,"shape_factor (Healthy, Fp1)","shape_factor (Alzheimer, Fp1)","shape_factor (Healthy, Fp1) vs shape_factor (A..."
1,Fp2,shape_factor,-1.623206,0.104545,0.248295,fdr_bh,0.05,False,wilcoxon-rank-sum,29,36,"shape_factor (Healthy, Fp2)","shape_factor (Alzheimer, Fp2)","shape_factor (Healthy, Fp2) vs shape_factor (A..."
2,F3,shape_factor,-1.992716,0.046293,0.219890,fdr_bh,0.05,False,wilcoxon-rank-sum,29,36,"shape_factor (Healthy, F3)","shape_factor (Alzheimer, F3)","shape_factor (Healthy, F3) vs shape_factor (Al..."
3,F4,shape_factor,-2.401816,0.016314,0.178813,fdr_bh,0.05,False,wilcoxon-rank-sum,29,36,"shape_factor (Healthy, F4)","shape_factor (Alzheimer, F4)","shape_factor (Healthy, F4) vs shape_factor (Al..."
4,C3,shape_factor,-1.438450,0.150306,0.315115,fdr_bh,0.05,False,wilcoxon-rank-sum,29,36,"shape_factor (Healthy, C3)","shape_factor (Alzheimer, C3)","shape_factor (Healthy, C3) vs shape_factor (Al..."
5,C4,shape_factor,-1.741977,0.081513,0.221248,fdr_bh,0.05,False,wilcoxon-rank-sum,29,36,"shape_factor (Healthy, C4)","shape_factor (Alzheimer, C4)","shape_factor (Healthy, C4) vs shape_factor (Al..."
6,P3,shape_factor,0.026394,0.978943,0.978943,fdr_bh,0.05,False,wilcoxon-rank-sum,29,36,"shape_factor (Healthy, P3)","shape_factor (Alzheimer, P3)","shape_factor (Healthy, P3) vs shape_factor (Al..."
7,P4,shape_factor,-1.121727,0.261978,0.451403,fdr_bh,0.05,False,wilcoxon-rank-sum,29,36,"shape_factor (Healthy, P4)","shape_factor (Alzheimer, P4)","shape_factor (Healthy, P4) vs shape_factor (Al..."
8,O1,shape_factor,-0.395904,0.692176,0.773608,fdr_bh,0.05,False,wilcoxon-rank-sum,29,36,"shape_factor (Healthy, O1)","shape_factor (Alzheimer, O1)","shape_factor (Healthy, O1) vs shape_factor (Al..."
9,O2,shape_factor,-0.567462,0.570400,0.677350,fdr_bh,0.05,False,wilcoxon-rank-sum,29,36,"shape_factor (Healthy, O2)","shape_factor (Alzheimer, O2)","shape_factor (Healthy, O2) vs shape_factor (Al..."
10,F7,shape_factor,-1.755173,0.079230,0.221248,fdr_bh,0.05,False,wilcoxon-rank-sum,29,36,"shape_factor (Healthy, F7)","shape_factor (Alzheimer, F7)","shape_factor (Healthy, F7) vs shape_factor (Al..."
11,F8,shape_factor,-2.349029,0.018822,0.178813,fdr_bh,0.05,False,wilcoxon-rank-sum,29,36,"shape_factor (Healthy, F8)","shape_factor (Alzheimer, F8)","shape_factor (Healthy, F8) vs shape_factor (Al..."
12,T3,shape_factor,-0.620249,0.535094,0.677350,fdr_bh,0.05,False,wilcoxon-rank-sum,29,36,"shape_factor (Healthy, T3)","shape_factor (Alzheimer, T3)","shape_factor (Healthy, T3) vs shape_factor (Al..."
13,T4,shape_factor,-1.755173,0.079230,0.221248,fdr_bh,0.05,False,wilcoxon-rank-sum,29,36,"shape_factor (Healthy, T4)","shape_factor (Alzheimer, T4)","shape_factor (Healthy, T4) vs shape_factor (Al..."
14,T5,shape_factor,-0.158362,0.874172,0.922737,fdr_bh,0.05,False,wilcoxon-rank-sum,29,36,"shape_factor (Healthy, T5)","shape_factor (Alzheimer, T5)","shape_factor (Healthy, T5) vs shape_factor (Al..."
15,T6,shape_factor,-0.778611,0.436209,0.637536,fdr_bh,0.05,False,wilcoxon-rank-sum,29,36,"shape_factor (Healthy, T6)","shape_factor (Alzheimer, T6)","shape_factor (Healthy, T6) vs shape_factor (Al..."
16,Fz,shape_factor,-0.607052,0.543816,0.677350,fdr_bh,0.05,False,wilcoxon-rank-sum,29,36,"shape_factor (Healthy, Fz)","shape_factor (Alzheimer, Fz)","shape_factor (Healthy, Fz) vs shape_factor (Al..."
17,Cz,shape_factor,-1.385663,0.165850,0.315115,fdr_bh,0.05,False,wilcoxon-rank-sum,29,36,"shape_factor (Healthy, Cz)","shape_factor (Alzheimer, Cz)","shape_factor (Healthy, Cz) vs shape_factor (Al..."
18,Pz,shape_factor,-1.068940,0.285097,0.451403,fdr_bh,0.05,False,wilcoxon-rank-sum,29,36,"shape_factor (Healthy, Pz)","shape_factor (Alzheimer, Pz)","shape_factor (Healthy, Pz) vs shape_factor (Al..."